export const CarModel =   {
  Masked: false,
  _id: "",
  Images: [
    {
      Color: "rouge",
      Images: ["../assets/marketplace/rename.png"],
    },
  ],
  Modele: "Tiggo  8 pro",
  Garentie: "2 years",
  Disponabilite: "Disponible",
  Prix_TTC: 155000,
  Moteur: "1.4",
  PromoObj: {
    IsPromo: false,
    Start: "2022-01-01T00:00:00.000Z",
    End: "2022-12-31T00:00:00.000Z",
    Value: 10,
  },
  MoteurObj: {
    Energie: "essence",
    Motricite: "4x4",
    Type_Moteur: "Type X",
    Cylidree: 0,
    Boite: "automatique",
    Consomation: "Low",
    Puissance: 100,
    Nombre_Cylindres: "0",
    Soupapes: 0,
    Accelaration: 2.9,
    Puissance_Tr: 100,
    Turbo: false,
    Nombre_Rapport_Boite: 1,
    Vitesse_Max: 250,
    Couple: 100,
  },
  ConfortObj: {
    Climatisation: "Auto",
    Direction: "Assistee",
    Ecran: "15 inch",
    Accoudoir: "Leather",
    Sieges_Chauffants: false,
    Boire_A_Gants_Refrigerante: false,
    Ordinateur_De__Bord: false,
    Radar_De_Recul: false,
    Autoradio: "Bluetooth",
    bluetooth: false,
  },
  SecurityObj: {
    Airbag: 8,
    Regulateur_Limiteur_de_Vitesse: "Yes",
    Abs: false,
    Keyless: "Yes",
    Esp: false,
    Détecteur_Angle_Mort: false,
    Aide_Demarrage_Cote: false,
    Anti_Demarrage: false,
    Verrouillage_Centralise: "Yes",
    Alarme: "Yes",
  },
  LookObj: {
    Feux_Anti_Arouillard: ["LED"],
    Feux_Avant: "LED",
    Peinture_Metalisee: false,
    Toit: false,
    Vitres_Teintees: false,
    Feux_Jour: "LED",
    Feux_Arriere: "LED",
    Jantes: 20,
    Couleur_Poignees: "Black",
    Dimension_Pneumatique: "235/45 R20",
  },
  VehiculeObj: {
    Volume_Coffre: 500,
    Longueur: 5000,
    Largeur: 2000,
    Hauteur: 1500,
    Empattement: 3000,
    Suspension_Avant: "Independent",
    Suspension_Arriere: "Independent",
    Nombre_Places: 5,
    Nombre_Portes: 4,
    Reservoir: 0,
  },
  createdAt: "2024-03-26T22:40:55.502Z",
  updatedAt: "2024-03-26T22:40:55.502Z",
  __v: 0,
}
export const emptyCarModel = {

  Images: [
    {
      Color: "",
      Images: [""],
    },
  ],
  Modele: "",
  Garentie: "",
  Disponabilite: "",
  Prix_TTC: 0,
  Moteur: "",
  PromoObj: {
    IsPromo: false,
    Start: "",
    End: "",
    Value:0 ,
  },
  MoteurObj: {
    Energie: "",
    Motricite: "",
    Type_Moteur: "",
    Cylidree: 0,
    Boite: "",
    Consomation: "",
    Puissance: 0,
    Nombre_Cylindres: "",
    Soupapes: 0,
    Accelaration: 0,
    Puissance_Tr: 0,
    Turbo: false,
    Nombre_Rapport_Boite: 9,
    Vitesse_Max: 0,
    Couple: 0,
  },
  ConfortObj: {
    Climatisation: "",
    Direction: "",
    Ecran: " ",
    Accoudoir: "",
    Sieges_Chauffants: false,
    Boire_A_Gants_Refrigerante: false,
    Ordinateur_De__Bord: false,
    Radar_De_Recul: false,
    Autoradio: "",
    bluetooth: false,
  },
  SecurityObj: {
    Airbag: 0,
    Regulateur_Limiteur_de_Vitesse: "",
    Abs: false,
    Keyless: "",
    Esp: false,
    Détecteur_Angle_Mort: false,
    Aide_Demarrage_Cote: false,
    Anti_Demarrage: false,
    Verrouillage_Centralise: "",
    Alarme: "",
  },
  LookObj: {
    Feux_Anti_Arouillard: [""],
    Feux_Avant: "",
    Peinture_Metalisee: false,
    Toit: false,
    Vitres_Teintees: false,
    Feux_Jour: "",
    Feux_Arriere: "LD",
    Jantes: 0,
    Couleur_Poignees: "",
    Dimension_Pneumatique: "",
  },
  VehiculeObj: {
    Volume_Coffre: 0,
    Longueur: 0,
    Largeur: 0,
    Hauteur: 0,
    Empattement: 0,
    Suspension_Avant: "",
    Suspension_Arriere: "",
    Nombre_Places: 0,
    Nombre_Portes: 0,
    Reservoir: 0,
  },

}