export const CarModel = {
    _id: "",
    Modele: "",
    Moteur: "",
    Garentie: "",
    Prix_TTC: 0,
    Disponabilite: "",
    createdAt: "",
    updatedAt: "",
    __v: 0,
    
    MoteurObj: {
      Energie: "",
      Motricite: "",
      Type_Moteur: "",
      Cylidree: 0,
      Boite: "",
      Consomation: "",
      Puissance: 0,
      Nombre_Cylindres: "",
      Soupapes: 0,
      Accelaration: 0,
      Puissance_Tr: 0,
      Turbo: false,
      Nombre_Rapport_Boite: 0,
      Vitesse_Max: 0,
      Couple: 0,
    },
    VehiculeObj: {
      Volume_Coffre: 0,
      Longueur: 0,
      Largeur: 0,
      Hauteur: 0,
      Empattement: 0,
      Suspension_Avant: "",
      Suspension_Arriere: "",
      Nombre_Places: 0,
      Nombre_Portes: 0,
      Reservoir: 0,
    },
    LookObj:{
      Feux_Anti_Arouillard: ["", ""],
      Feux_Avant: "",
      Peinture_Metalisee: false,
      Toit: false,
      Vitres_Teintees: false,
      Feux_Jour: "",
      Feux_Arriere: "",
      Jantes: 0,
      Couleur_Poignees: "",
      Dimension_Pneumatique: "",
    },ConfortObj:{
      Climatisation: "",
      Direction: "",
      Ecran: "",
      Accoudoir: "",
      Sieges_Chauffants: false,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: false,
      Radar_De_Recul: false,
      Autoradio: "",
      bluetooth: false,
    },
    SecurityObj:{
      Airbag: 0,
      Regulateur_Limiteur_de_Vitesse: "",
      Abs: false,
      Keyless: "",
      Esp: false,
      Détecteur_Angle_Mort: false,
      Aide_Demarrage_Cote: false,
      Anti_Demarrage: false,
      Verrouillage_Centralise: "",
      Alarme: "",
    },
    PromoObj: {
      IsPromo: false,
      Start: "",
      End: "",
      Value: 0,
    },
    Images: [],
  };