const data = [
  {
    Name: "souchi ala eddine",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "zerkhef abd arraoufbe=",
    Phone: "0677889900",
    Email: "clieddddddddddddddddddddddddddddddddddnt@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "benferhat mohamed ouelhadj aymen",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
  {
    Name: "alaa",
    Phone: "0677889900",
    Email: "client@client.dz",
    Model: "tiggo 8 pro",
    Vin: "fqsfldsjflqsmdjf",
    Prix_Vente: 150000,
    Adresse: "msila",
    Data_Achat: "15-03-2024",
    Documents: ["document1", "document2", "document3"],
    img: "../assets/clients/profile.png",
    id: "first",
  },
];
export default data;
